(defun c:Lam1 (/ x1 x2 y1 y2 m n ss D lam lami SD L1 L2 &k1 &k2 %k1 %k2 pt po)
	(setvar "cmdecho" 0)
	(setvar "blipmode" 0)
	(setvar "dimzin" 0)
	(vl-load-com)
	(setq m 0 lam '())
	(princ "\n select SD")
	(setq SD (ssget '((0 . "LWPOLYLINE")(8 . "SD"))))
	(setq L1 (sslength SD))
	(princ "\n select lamination1")
	(setq lami (ssget '((0 . "CIRCLE")(8 . "lamination template 1"))))
	(if(/= lami nil)
		(progn
			(setq L2 (sslength lami))
			(repeat L2
				(setq &k2 (entget (ssname lami m))
					%k2(cdr(assoc 10 &k2))
					lam(cons %k2 lam)
					m (+ m 1)
				)
			)
			(setq m 0)
		)
	)
	(setq lam (reverse lam))
	(setq n 0)
	(repeat L1
		(repeat L2
			(setq po (vlax-ename->vla-object (ssname SD n)))
			(setq pt (vlax-curve-getClosestPointTo po (nth m lam) t))
			(setq D (distance (nth m lam) pt))
			(princ D)
			(princ "\n")
			(if(<= D 1.75)
				(progn
					(entdel(ssname lami m))
				)
			)
			(setq m (+ m 1))
		)
		(setq n (+ n 1))
		(setq m 0)
	)
)
