(defun c:Lam2 (/ x1 x2 y1 y2 m n ss PD D lam lamII lami lami2 MP L1 L2 L3 L4 &k1 &k2 %k1 %k2 pt po)
	(setvar "cmdecho" 0)
	(setvar "blipmode" 0)
	(setvar "dimzin" 0)
	(vl-load-com)
	(setq n 0 ss '())
	(setq m 0 lam '())
	(setq lamII '())
	(princ "\n select PD-C")
	(setq PD (ssget '((0 . "LWPOLYLINE")(8 . "PD-C"))))
	(setq L3 (sslength PD))
	(princ "\n select MP")
	(setq MP (ssget '((0 . "CIRCLE")(8 . "MP"))))
	(if(/= MP nil)
		(progn
			(setq L1 (sslength MP))
			(repeat L1
				(setq &k1 (entget (ssname MP n))
					%k1(cdr(assoc 10 &k1));;取得圆心坐标
					ss(cons %k1 ss)
					n (+ n 1)
				)
			)
			(setq n 0)
		)
		(close ff)
	)
	(princ "\n select lamination2")
	(setq lami (ssget '((0 . "CIRCLE")(8 . "lamination template 2"))))
	(if(/= lami nil)
		(progn
			(setq L2 (sslength lami))
			(repeat L2
				(setq &k2 (entget (ssname lami m))
					%k2(cdr(assoc 10 &k2))
					lam(cons %k2 lam)
					m (+ m 1)
				)
			)
			(setq m 0)
		)
	)
	(setq lam (reverse lam))
	(repeat L1
		(repeat L2
			(setq D (distance (nth n ss)(nth m lam)))
			(if(<= D 11.75)
				(progn
					(entdel(ssname lami m))
					;(command "change" (ssname lami m) "" "p" "la" "0" "")
				)
			)
			(setq m (+ m 1))
		)
		(setq n (+ n 1))
		(setq m 0)
	)
	(princ "\n select lamination2")
	(setq lami2 (ssget '((0 . "CIRCLE")(8 . "lamination template 2"))))
	(if(/= lami2 nil)
		(progn
			(setq L4 (sslength lami2))
			(repeat L4
				(setq &k2 (entget (ssname lami2 m))
					%k2(cdr(assoc 10 &k2))
					lamII(cons %k2 lamII)
					m (+ m 1)
				)
			)
			(setq m 0)
		)
	)
	(setq lamII (reverse lamII))
	(setq n 0)
	(repeat L3
		(repeat L4
			(setq po (vlax-ename->vla-object (ssname PD n)))
			(setq pt (vlax-curve-getClosestPointTo po (nth m lamII) t))
			(setq D (distance (nth m lamII) pt))
			(princ D)
			(princ "\n")
			(if(<= D 11.75)
				(progn
					(entdel(ssname lami2 m))
				)
			)
			(setq m (+ m 1))
		)
		(setq n (+ n 1))
		(setq m 0)
	)
)
